baseURL = "/"
languageCode = 'en-us'
title = 'Aashraya Enclave'
theme = "PaperMod"

publishDir = "docs"

[params]
  ShowReadingTime = true
  ShowBreadCrumbs = true
  ShowToc = true
  defaultTheme = "light"
