baseURL = "/"
languageCode = 'en-us'
title = 'Aashraya Enclave'
theme = "PaperMod"

publishDir = "docs"

[params]
  ShowReadingTime = true
  ShowBreadCrumbs = true
  ShowToc = true
  defaultTheme = "light"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[params.shareButtons]
  size = "small"
  networks = ["facebook", "twitter", "whatsapp", "email"]


