[[redirects]]
  from = "/admin"
  to = "/admin/index.html"
  status = 200

[build]
  command = "hugo"
  publish = "docs"

[context.production.environment]
  HUGO_VERSION = "0.125.7"
  HUGO_ENV = "production"


